/** English cabinet strings. Ukrainian UI stays the source text. */
export const WORK_EN: Record<string, string> = {
  " с": " s",
  "4г": "4h",
  "7д": "7d",
  "Ні": "No",
  "Ти": "You",
  "30д": "30d",
  "90д": "90d",
  "Так": "Yes",
  "Усе": "All",
  "Лонг": "Long",
  "Пара": "Pair",
  "Стоп": "Stop",
  "Шорт": "Short",
  "вимк": "off",
  "стоп": "stop",
  "Агент": "Agent",
  "Клас ": "Class ",
  "Огляд": "Overview",
  "Події": "Events",
  "Праця": "Work",
  "Арбітраж": "Arbitrage",
  "Ончейн не відповів.": "On-chain did not answer.",
  "Чистий край": "Net edge",
  "Чекаю.": "Waiting.",
  "сигнал є, ногу не відправляю.": "signal only, the leg is not sent.",
  "Гаманець": "Wallet",
  "Магазин": "Shop",
  "Акції": "Shares",
  "Ключ і баланси": "Key and balances",
  "Агенти в лімітах": "Agents within limits",
  "Купити агента": "Buy an agent",
  "Купівля акцій": "Buy shares",
  "Робочий стіл": "Work desk",
  "Соларчик · тестовий Devnet": "Solarchik · Devnet test",
  "Мережа Solana": "Solana network",
  "Перевірка столу": "Desk check",
  "Перевірити і виправити": "Check and fix",
  "Перевіряю…": "Checking…",
  "Чекаю гаманець…": "Waiting for the wallet…",
  "Сховище пише.": "Storage writes.",
  "Сховище не зберегло запис.": "Storage did not keep the write.",
  "Сховище заблоковане. Відкрий звичайне вікно.": "Storage is blocked. Open a normal window.",
  "Перемкнув Devnet на публічний вузол.": "Switched Devnet to the public node.",
  "Devnet живий.": "Devnet is up.",
  "Devnet не відповідає.": "Devnet did not answer.",
  "Mainnet живий.": "Mainnet is up.",
  "Mainnet не відповідає.": "Mainnet did not answer.",
  "Створив гаманець на цьому пристрої.": "Created a wallet on this device.",
  "Баланс зчитав знову.": "Read the balance again.",
  "Гаманець на місці.": "The wallet is in place.",
  "Баланс Devnet не зчитався.": "Devnet balance did not come back.",
  "Гаманець не створився.": "The wallet was not created.",
  "Гаманець не відкрився.": "The wallet did not open.",
  "Ключ не розшифрувався. Встав записаний секрет.": "The key did not unlock. Paste the saved secret.",
  "Голос готовий.": "Voice is ready.",
  "Голос був вимкнений. Увімкнув.": "Voice was off. Turned it on.",
  "Голос увімкнув і зняв зависання.": "Turned voice on and unstuck it.",
  "Зняв зависання голосу.": "Unstuck the voice.",
  "Звук чекає натискання кнопки.": "Sound is waiting for a button press.",
  "Голос увімкнув, але браузер ще блокує звук. Натисни кнопку ще раз.": "Voice is on, but the browser still blocks sound. Press the button again.",
  "У цьому вікні немає звуку.": "This window has no sound.",
  "Агент відповів.": "The agent answered.",
  "Агент не відповів.": "The agent did not answer.",
  "Перевірка готова.": "Check is done.",
  "Сховище": "Storage",
  "Голос": "Voice",
  "Стіл": "Desk",
  "читаю мережу…": "reading the network…",
  "жива": "up",
  "немає зв'язку": "no connection",
  "немає слота": "no slot",
  "RPC відмовив": "RPC refused",
  " мс": " ms",
  "слот ": "slot ",
  "Відкрити магазин": "Open the shop",
  "Немає агента. Купіть готового в Магазині.": "No agent yet. Buy a ready one in the Shop.",
  "Тут агент працює сам, у межах лімітів. Немає агента — візьми його в Магазині.": "The agent works on its own, inside the limits. No agent yet — get one in the Shop.",
  "немає": "none",
  "пауза": "paused",
  "події": "events",
  "увімк": "on",
  "читаю": "reading",
  "1 доба": "1 day",
  "2 доби": "2 days",
  "Агенти": "Agents",
  "Боти: ": "Bots: ",
  "Вільно": "Free",
  "Журнал": "Log",
  "Крипто": "Crypto",
  "Куди: ": "To: ",
  "Погода": "Weather",
  "Продаж": "Sell",
  "Профіт": "Profit",
  "Робота": "Job",
  "очікує": "waiting",
  "погода": "weather",
  "працює": "working",
  "стоїть": "idle",
  "читаю…": "reading…",
  "Гаманці": "Wallets",
  "Депозит": "Deposit",
  "Закрито": "Closed",
  "Купівля": "Buy",
  "Кімната": "Room",
  "Профіль": "Profile",
  "Станція": "Station",
  "Сторона": "Side",
  "У ринку": "In market",
  "ще нема": "not yet",
  "Адреса: ": "Address: ",
  "Виведено": "Withdrawn",
  "Вторинка": "Resale",
  "Мережа: ": "Network: ",
  "Резолв: ": "Resolve: ",
  "Сума DCA": "DCA amount",
  "Точність": "Accuracy",
  "У ринках": "In markets",
  "в роботі": "at work",
  "вимкнено": "off",
  "застарів": "stale",
  "створюю…": "creating…",
  " · дельта": " · delta",
  "Бот подій": "Events bot",
  "Надіслати": "Send",
  "Поповнити": "Top up",
  "На касу арбу": "To the arb desk",
  "Каса арбу. Не секретар.": "Arb desk. Not the secretary.",
  "Арбітраж працює сам. Стріляє лише коли є край і каса.": "Arb runs by itself. It fires only when there is an edge and a funded desk.",
  "Нога менша за мінімум біржі.": "The leg is below the exchange minimum.",
  "Немає цієї пари на Backpack.": "Backpack does not list this pair.",
  "Чекаю ціну SOL.": "Waiting for the SOL price.",
  "усі Solana-пари": "all Solana pairs",
  "Читаю книгу Backpack…": "Reading the Backpack book…",
  "Чекаю касу.": "Waiting for the desk.",
  "Край.": "Edge.",
  "Немає кредиту.": "No credit.",
  "Каса Backpack порожня.": "Backpack desk is empty.",
  "Ончейн-каса порожня.": "On-chain desk is empty.",
  "Немає ключа каси ончейн.": "No on-chain desk key.",
  "Зламано, чекає зведення.": "Broken, waiting to square.",
  "Прогнозів": "Forecasts",
  "Скасувати": "Cancel",
  "Сума in: ": "Amount in: ",
  "немає NFT": "no NFT",
  "увімкнено": "on",
  "Крипто-бот": "Crypto bot",
  "Мої токени": "My tokens",
  "сума немає": "no amount",
  "SOL кімнати": "Room SOL",
  "З гаманця: ": "From wallet: ",
  "Підтвердити": "Confirm",
  "безкоштовно": "free",
  "немає цифри": "no figure",
  "читаю USDC…": "reading USDC…",
  " акц. · bid ": " sh. · bid ",
  "SOL на акцію": "SOL per share",
  "USDC кімнати": "Room USDC",
  "Виставити · ": "List · ",
  "Ліміт сесії ": "Session limit ",
  "завантаження": "loading",
  "Готовий агент": "Ready agent",
  "Напиши агенту": "Write to the agent",
  "не підключено": "not connected",
  "створюю ключ…": "creating key…",
  "читаю Devnet…": "reading Devnet…",
  "Вивести Devnet": "Withdraw Devnet",
  "Відкрити Store": "Open Store",
  "Відкрити Працю": "Open Work",
  "Депозит у pUSD": "Deposit to pUSD",
  "Повернути ключ": "Return the key",
  "Статус моста: ": "Bridge status: ",
  "читаю mainnet…": "reading mainnet…",
  "Агент на паузі.": "Agent is paused.",
  "Кімната агентів": "Agent room",
  "Мережа: Mainnet": "Network: Mainnet",
  "Мережа: Polygon": "Network: Polygon",
  "Погасити виграш": "Redeem winnings",
  "Показати секрет": "Show secret",
  "Підтверди угоду": "Confirm the trade",
  "Усього в угодах": "Total in trades",
  "актив не обрано": "no asset picked",
  "створюю адресу…": "creating address…",
  "Адреса кімнати: ": "Room address: ",
  "NFT не підключено": "NFT not connected",
  "Інтервал DCA, сек": "DCA interval, sec",
  "Адреса отримувача": "Recipient address",
  "Взяти і працювати": "Take and work",
  "Дрібні живі угоди": "Small live trades",
  "Очікуваний USDC: ": "Expected USDC: ",
  "Повернути Polygon": "Return Polygon",
  "Сума виводу в SOL": "Withdraw amount in SOL",
  "Phantom підключено": "Phantom connected",
  "Є відкритий ордер.": "There is an open order.",
  "Адреса Polygon 0x…": "Polygon address 0x…",
  "Адресу скопійовано": "Address copied",
  "Вивести SOL агента": "Withdraw agent SOL",
  "Підключити Phantom": "Connect Phantom",
  "немає адреси моста": "no bridge address",
  "читаю котирування…": "reading quote…",
  " pUSD · ціна входу ": " pUSD · entry price ",
  "Jupiter не відповів": "Jupiter did not answer",
  "Відкрити сайт Slice": "Open Slice site",
  "Купити з стратегією": "Buy with strategy",
  "лише комісія мережі": "network fee only",
  "чекає підтвердження": "waiting for confirmation",
  "читаю адресу моста…": "reading bridge address…",
  "Гаманець створюється": "Wallet is being created",
  "Купити ключем агента": "Buy with the agent key",
  "Секрет не відкрився.": "Secret did not open.",
  " · адресу скопійовано": " · address copied",
  "Ключ кімнати · Devnet": "Room key · Devnet",
  "Сума поповнення в SOL": "Top-up amount in SOL",
  "Показати секрет ще раз": "Show secret again",
  "Розрив з Coinbase, bps": "Coinbase gap, bps",
  "Вивести pUSD Polymarket": "Withdraw Polymarket pUSD",
  "Показати секрет Polygon": "Show Polygon secret",
  "Стратегію ще не зчитано": "Strategy not read yet",
  " SOL. Торговий гаманець:": " SOL. Trading wallet:",
  "Гаманця агента ще немає.": "The agent wallet is not here yet.",
  "Записаний секрет Polygon": "Saved Polygon secret",
  "Розумію, що це живий SOL": "I understand this is live SOL",
  "Скасувати ордер у стакані": "Cancel the book order",
  "Поки тихо. Натисніть Work.": "Quiet for now. Press Work.",
  "Вставити секрет Polygon 0x…": "Paste Polygon secret 0x…",
  "Поповни pUSD. Агент стоїть.": "Top up pUSD. The agent is idle.",
  "Соларчик · QuickNode Devnet": "Solarchik · QuickNode Devnet",
  "Секрет Polygon не відкрився.": "Polygon secret did not open.",
  "Архів цієї смуги ще порожній.": "This lane's archive is still empty.",
  "Живий своп Jupiter на mainnet": "Live Jupiter swap on mainnet",
  "Записаний секрет ключа кімнати": "Saved room-key secret",
  "Показати секрет Polygon ще раз": "Show Polygon secret again",
  "Цей токен зараз не веде зміну.": "This token is not on shift right now.",
  " Поповни гаманець. Боти стоять.": " Top up the wallet. Bots are idle.",
  "Вставити записаний секрет ключа": "Paste the saved room-key secret",
  "Створюю ключ на цьому пристрої…": "Creating a key on this device…",
  ". Списує ключ кімнати на Devnet.": ". Charges the room key on Devnet.",
  "Phantom · не підписує живий своп": "Phantom · does not sign the live swap",
  "Агент працює сам у межах лімітів": "The agent works on its own inside the limits",
  "Агент у черзі до наступного вікна.": "The agent is queued for the next window.",
  "Зараз у відкритих ринках порожньо.": "Open markets are empty right now.",
  "Grok ще відповідає. Нову не ставлю.": "Grok is still answering. I am not placing a new one.",
  "Секрет Polygon. Скопіюй сам і сховай.": "Polygon secret. Copy it yourself and hide it.",
  "TWAP 30s немає цифри / 60s немає цифри": "TWAP 30s no figure / 60s no figure",
  "Живий ордер Polymarket CLOB на Polygon": "Live Polymarket CLOB order on Polygon",
  "Кнопка «Поповнити» — лише кран Devnet.": "The Top up button is only the Devnet faucet.",
  "Немає агента. Купіть готового в Store.": "No agent. Buy a ready one in Store.",
  "Live, ще без fill. Продажу акцій немає.": "Live, no fill yet. No share selling.",
  "Поповни торговий гаманець. Боти стоять.": "Top up the trading wallet. Bots are idle.",
  "Секрет ключа кімнати. Скопіюй сам і сховай.": "Room-key secret. Copy it yourself and hide it.",
  "Комісія мінту — Devnet. Mainnet сюди не йде.": "Mint fee is Devnet. Mainnet does not go here.",
  "Ринок порожній. Виставте свого агента з Праці.": "The market is empty. List your agent from Work.",
  "Агент закрив вікно в плюс і стоїть до наступного.": "The agent closed the window in profit and waits for the next one.",
  "Депозит Polymarket Bridge. Solana → pUSD на Polygon": "Polymarket Bridge deposit. Solana → pUSD on Polygon",
  "Торговий гаманець підключено. Живий режим ще вимкнений.": "Trading wallet connected. Live mode is still off.",
  "Ставка в ринку. Агент чекає кінець вікна, щоб закрити її.": "Bet is in the market. The agent waits for the window to end so it can close it.",
  "Газ Polygon цим депозитом може не прийти. Кинь трохи POL на ": "Polygon gas may not arrive with this deposit. Send a little POL to ",
  "Суму виграшу не показую, поки мережа не віддасть новий pUSD.": "I do not show the win amount until the network returns the new pUSD.",
  "Запиши секрет ключа, потім надсилай mainnet SOL на цю адресу.": "Write down the key secret, then send mainnet SOL to this address.",
  "Готовий агент одразу в роботу. Вторинка — токени, які вже виставили.": "A ready agent goes straight to work. Resale is tokens already listed.",
  "Натисни «Показати секрет ще раз». Після цього він з’явиться лише тут.": "Press Show secret again. After that it appears only here.",
  "Це не Jupiter. USDC/SOL з кімнати на цю SVM-адресу стає pUSD на Polygon.": "This is not Jupiter. USDC/SOL from the room to this SVM address becomes pUSD on Polygon.",
  "Без запису секрету ключ зникне разом із браузером. Секрет не йде на сервер.": "Without saving the secret, the key disappears with the browser. The secret does not go to the server.",
  "Купуєте NFT і одразу тиснете Work. Ставки йдуть тестовим SOL цього гаманця.": "You buy the NFT and press Work. Bets use this wallet's test SOL.",
  "Phantom у цьому вікні немає. На Android гаманець Solana відкривається в Chrome. Фейковий конект не ставлю.": "Phantom is not in this window. On Android the Solana wallet opens in Chrome. I do not put a fake connect.",
  "Покупка йде ключем гаманця агента через Jupiter, ті самі акції що на Slice. Сайт Slice окремо не бачить цей ключ.": "The buy uses the agent wallet key through Jupiter, the same shares as on Slice. The Slice site does not see this key.",
  "Гаманець створюється з першого заходу. Біткоїн-бот ставить на 15 хв Up/Down. Події і погода — окремі смуги. У Праці в кожного є огляд і ціль.": "The wallet is created on the first visit. The Bitcoin bot bets 15 min Up/Down. Events and weather are separate lanes. In Work each one has an overview and a goal.",
  "Біткоїн-бот ставить на вікна, які ввімкнені: 5 хв, 15 хв, 1 год, 4 год. Бік вирішує Grok. Купівля лише якщо ask цього боку в коридорі і слот вільний. Події і погода — окремо, від 65%.": "The Bitcoin bot bets the windows that are on: 5 min, 15 min, 1 hour, 4 hours. Grok picks the side. A buy happens only if that side's ask is inside the band and the slot is free. Events and weather are separate, from 65%.",
  "Ключ не розшифрувався": "The key did not decrypt",
  "Ключ Polygon не розшифрувався. Встав записаний секрет.": "The Polygon key did not decrypt. Paste the saved secret.",
  "Секрет Polygon не підійшов. Гаманець не замінив.": "The Polygon secret did not fit. The wallet was not replaced.",
  "контракт створено": "contract created",
  "Поповни гаманець. Боти стоять.": "Top up the wallet. Bots are idle.",
  "Пісочниця. Це тестовий переказ Devnet. Мейннет лише читання": "Sandbox. This is a Devnet test transfer. Mainnet is read-only",
  ", вузол живий": ", node is live",
  "Баланс не вигадую.": "I am not inventing the balance.",
  "Скопіювати ": "Copy ",
  "уже на цьому пристрої. Поповнення і вивід — у шапці.": "is already on this device. Top up and withdraw are in the header.",
  "Крипто 15хв ": "Crypto 15m ",
  "вікно ": "window ",
  " с до резолву": " s to resolve",
  " акц.": " sh.",
  "станція ": "station ",
  "Сесія ": "Session ",
  " · доба ": " · day ",
  "Jupiter (лише читання): близько ": "Jupiter (read only): about ",
  " USDC за ": " USDC for ",
  "Мої агенти": "My agents",
  "Додати агента": "Add an agent",
  "Запустити": "Start",
  "Перформанс": "Performance",
  "Історія угод": "Trade history",
  "Стратегія": "Strategy",
  "Зважений": "Weighted",
  "Чат": "Chat",
  "Епоха": "Epoch",
  "Смуги": "Lanes",
  "Оновити": "Refresh",
  "Кошти в ринках": "Funds in markets",
  "Ончейн · тестовий SOL": "On-chain · test SOL",
  "тільки buy": "buy only",
  "тільки sell": "sell only",
  "buy і sell": "buy and sell",
  "Коридор ask. Поза ним ордера немає.": "Ask band. Outside it there is no order.",
  "Спорт не вмикається. Горизонт резолву:": "Sports stay off. Resolve horizon:",
  "Вікна, на які ставить крипта. Чат міняє той самий список.": "Windows the crypto bot bets. Chat changes the same list.",
  "Ще тихо. Запусти агента — сюди ляжуть ринки, сторона і сума.": "Still quiet. Start the agent — markets, side and size land here.",
  "Кожен відрізок починається з нуля і показує рух PnL закритих угод.": "Each stretch starts at zero and shows closed-trade PnL.",
  "Час поточного вікна. Ставка сидить у ринку, доки вікно не закриється.": "Time left in this window. The bet stays in the market until the window closes.",
  "Розмір угоди залежить від руху ринку, впевненості агента і вільних коштів.": "Size depends on the market move, the agent's confidence and free funds.",
  "Розмір угоди залежить від руху ринку, впевненості агента і вільних коштів. Край і": "Size depends on the market move, the agent's confidence and free funds. Edge and",
  "лишаються помірними.": "stay moderate.",
  "закритих угод.": "closed trades.",
  "Кожен відрізок починається з нуля і показує рух ": "Each stretch starts at zero and shows the move ",
  "серія ": "streak ",
  "вер.": "ver.",
  "Боти:": "Bots:",
  "Сесія": "Session",
  "доба": "day",
  "вікно": "window",
  "Напиши звичайною мовою. Агент міняє смуги, ризик, вікна крипти (5 хв, 15 хв, 1 год, 4 год) і коридор ask. Ставить, якщо прямо попросиш.": "Write in plain language. The agent changes lanes, risk, crypto windows (5 min, 15 min, 1 hour, 4 hours) and the ask band. It bets only if you ask directly.",
  "Вивести з ринку": "Withdraw from the market",
  "Пауза": "Pause",
  "Заблоковано ": "Locked ",
  " SOL до кінця вікна.": " SOL until the window ends.",
  "Мінусів підряд: ": "Losses in a row: ",
  "Увімкни лише смуги цього NFT. Нових ринків тут немає. Робота ": "Turn on only this NFT's lanes. There are no new markets here. Job ",
  "Фʼючерс BTCUSDT, плече 2×, один слот. Це не Jupiter і не Polymarket.": "BTCUSDT futures, 2× leverage, one slot. This is not Jupiter and not Polymarket.",
  "Лише знятий high зі станції в правилах. Це не вимикається.": "Only the recorded high from the station in the rules. This does not turn off.",
  "DEX з Праці не запускається.": "DEX does not start from Work.",
  "Записати стратегію в NFT": "Write the strategy into the NFT",
  "від": "from",
  "до": "to",
  " хв": " min",
  " год": " h",
  "Секрет лишився в браузері.": "The secret stayed in the browser.",
  "Ключ ": "Key ",
  " на пристрої. На Devnet ": " is on this device. On Devnet ",
  " SOL. Вкажи суму й натисни «Поповнити».": " SOL. Type an amount and tap Top up.",
  "Prediction чекає NFT класу 1 або комбо": "Prediction is waiting for a class 1 NFT or a combo",
  "DEX чекає NFT класу 2 або комбо": "DEX is waiting for a class 2 NFT or a combo",
  "СИМУЛЯЦІЯ · devnet, без грошей": "SIMULATION · devnet, no money",
  "Кредит не списується. Mainnet вимкнено на сервері.": "Credit is not spent. Mainnet is off on the server.",
  "Mainnet вимкнено на сервері.": "Mainnet is off on the server.",
  "Каса закрита: немає спільної бази (DATABASE_URL), ліміти не перевірити.": "Desk closed: no shared database (DATABASE_URL), limits cannot be checked.",
  "Mainnet вимкнено: потрібна спільна база (DATABASE_URL).": "Mainnet is off: a shared database (DATABASE_URL) is required.",
  "Mainnet увімкнено на сервері. Ліміт каси 0.02 SOL на добу.": "Mainnet is on at the server. Desk cap 0.02 SOL per day.",
  "Каса закрита: база не відповіла.": "Desk closed: the database did not answer.",
  "Ліміт гаманця: зачекай 30 с або до завтра (UTC).": "Wallet limit: wait 30 s or until tomorrow (UTC).",
  "Ліміт каси: зачекай 30 с або денний ліміт вичерпано.": "Desk limit: wait 30 s, or the daily cap is used up.",
  "Цей NFT не в твоєму гаманці.": "This NFT is not in your wallet.",
  "Арбітраж лише для агента класу 2 або комбо.": "Arbitrage is only for a class 2 agent or a combo.",
  "Не вдалося перевірити NFT ончейн. Спробуй пізніше.": "Could not check the NFT on-chain. Try later.",
  "Цей підпис уже використано.": "This signature was already used.",
  "Підпис застарів. Спробуй ще раз.": "The signature expired. Try again.",
  "Підпис гаманця не збігся.": "The wallet signature did not match.",
  "Немає підпису гаманця.": "No wallet signature.",
  "Немає ключа кімнати.": "No room key.",
  "Не вдалося перевірити гаманець ончейн. Мінт не почато.": "Could not check the wallet on-chain. Mint not started.",
  "Безкоштовний мінт уже йде. Зачекай 10 хв.": "A free mint is already in progress. Wait 10 min.",
  "Сервер не підтвердив безкоштовний мінт. Мінт не почато.": "The server did not confirm the free mint. Mint not started.",
  "Сервер не відповів. Мінт не почато.": "The server did not answer. Mint not started.",
  "Безкоштовний агент уже є. Pro без комісії з прибутку.": "A free agent is already here. Pro takes no cut of profit.",
  "Підключи Phantom або гаманець телефону. Оплата з ключа кімнати не йде.": "Connect Phantom or the phone wallet. The room key does not pay.",
  "Seeker на mainnet. Оплата Pro поки лише Devnet. Нічого не списано.": "Seeker is on mainnet. Pro payment is devnet only for now. Nothing was charged.",
  "Pro · 0% комісії": "Pro · 0% fee",
  "Free · 5% прибутку": "Free · 5% of profit",
  "один безкоштовний на гаманець": "one free mint per wallet",
  "Агент на паузі. Угоду не відправляю.": "Agent is paused. The trade is not sent.",
  "Ліміт угоди": "Trade cap",
  "Денний ліміт": "Daily cap",
  "Ліміт збитків": "Loss cap",
  "Денний мінус": "Daily loss",
  "Угоду не відправляю.": "The trade is not sent.",
  "Комісію не відправлено. Підпис не вигадую.": "The fee was not sent. No signature was invented.",
  "Комісію не відправлено. Немає ключа.": "The fee was not sent. There is no key.",
  "Оплата з твого гаманця на казну…": "Paying the treasury from your wallet…",
  "прийнято. Мінт не пройшов.": "landed. The mint did not.",
  "Ліміти": "Limits",
  "Можна лише нижче стелі. Вище за стелю не ставиться.": "You can only set these lower. The ceiling does not move.",
  "Пауза агента": "Pause the agent",
  "Зняти паузу": "Resume",
  "вікно без комісії": "fee-free window",
  "мінус, комісії немає": "a loss, no fee",
  "папір, не відправлено": "paper, not sent",
};
