/** English cabinet strings. Ukrainian UI stays the source text. */
export const WORK_EN: Record<string, string> = {
  "Мало: сервер нарахував": "Too little: the server charged",
  "лампортів за цю позицію.": "lamports for this position.",
  "Відмітку підписав інший гаманець.": "The clock-in was signed by another wallet.",
  "Транзакцію відмітки не знайдено.": "Clock-in transaction not found.",
  "Транзакція відмітки впала.": "Clock-in transaction failed.",
  "Транзакція відмітки ще не в блоці.": "Clock-in transaction is not in a block yet.",
  "У транзакції немає мемо відмітки за цей день.": "The transaction has no clock-in memo for this day.",
  "Вікно вже запущено. Онови сторінку.": "Window already started. Reload the page.",
  "За цю позицію сервер комісії не нараховував.": "The server charged no fee for this position.",
  "Не вдалося закрити.": "Could not close.",
  "Позиція ще відкрита на сервері.": "The position is still open on the server.",
  "Сервер не бачив відкриття цієї позиції.": "The server never saw this position open.",
  "Сервер не бачить доступного вікна: потрібні підтверджені відмітки (7 днів поспіль або 30).": "The server sees no window to start: verified clock-ins needed (7 days in a row or 30).",
  "Сервер не має цієї позиції: комісію не звірено.": "The server has no record of this position: fee not verified.",
  "Сервер не прочитав ціну ринку.": "The server could not read the market price.",
  "Спершу сплати комісію:": "Pay the fee first:",
  "Ставка поза межами.": "Stake out of bounds.",
  "Цей NFT не належить гаманцю кімнати.": "This NFT is not owned by the room wallet.",
  "Цей id позиції вже зайнятий.": "This position id is already taken.",
  "Цей гаманець уже відмітився за іншу кімнату сьогодні.": "This wallet already clocked in for another room today.",
  "Цей день уже записано.": "This day is already recorded.",
  "Відмітка застара для сервера.": "Clock-in is too old for the server.",
  "Мережа не відповіла.": "Network did not answer.",
  "Немає бази (DATABASE_URL): сервер не веде позиції.": "No database (DATABASE_URL): the server keeps no positions.",
  "Немає бази.": "No database.",
  "Немає підпису гаманця кімнати.": "No room wallet signature.",
  "Погана адреса.": "Bad address.",
  "Погані дані відмітки.": "Bad clock-in data.",
  "Погані дані позиції.": "Bad position data.",
  "Підпис відмітки не збігся.": "Clock-in signature does not match.",
  " с": " s",
  "4г": "4h",
  "7д": "7d",
  "Ні": "No",
  "Ти": "You",
  "30д": "30d",
  "90д": "90d",
  "Так": "Yes",
  "Усе": "All",
  "Лонг": "Long",
  "Пара": "Pair",
  "Стоп": "Stop",
  "Шорт": "Short",
  "вимк": "off",
  "стоп": "stop",
  "Агент": "Agent",
  "Клас ": "Class ",
  "Огляд": "Overview",
  "Події": "Events",
  "Праця": "Work",
  "Арбітраж": "Arbitrage",
  "Ончейн не відповів.": "On-chain did not answer.",
  "Чистий край": "Net edge",
  "Чекаю.": "Waiting.",
  "сигнал є, ногу не відправляю.": "signal only, the leg is not sent.",
  "Гаманець": "Wallet",
  "Магазин": "Shop",
  "Акції": "Shares",
  "Ключ і баланси": "Key and balances",
  "Агенти в лімітах": "Agents within limits",
  "Купити агента": "Buy an agent",
  "Купівля акцій": "Buy shares",
  "Робочий стіл": "Work desk",
  "Соларчик · тестовий Devnet": "Solarchik · Devnet test",
  "Мережа Solana": "Solana network",
  "Перевірка столу": "Desk check",
  "Перевірити і виправити": "Check and fix",
  "Перевіряю…": "Checking…",
  "Чекаю гаманець…": "Waiting for the wallet…",
  "Сховище пише.": "Storage writes.",
  "Сховище не зберегло запис.": "Storage did not keep the write.",
  "Сховище заблоковане. Відкрий звичайне вікно.": "Storage is blocked. Open a normal window.",
  "Перемкнув Devnet на публічний вузол.": "Switched Devnet to the public node.",
  "Devnet живий.": "Devnet is up.",
  "Devnet не відповідає.": "Devnet did not answer.",
  "Mainnet живий.": "Mainnet is up.",
  "Mainnet не відповідає.": "Mainnet did not answer.",
  "Створив гаманець на цьому пристрої.": "Created a wallet on this device.",
  "Баланс зчитав знову.": "Read the balance again.",
  "Гаманець на місці.": "The wallet is in place.",
  "Баланс Devnet не зчитався.": "Devnet balance did not come back.",
  "Гаманець не створився.": "The wallet was not created.",
  "Гаманець не відкрився.": "The wallet did not open.",
  "Ключ не розшифрувався. Встав записаний секрет.": "The key did not unlock. Paste the saved secret.",
  "Голос готовий.": "Voice is ready.",
  "Голос був вимкнений. Увімкнув.": "Voice was off. Turned it on.",
  "Голос увімкнув і зняв зависання.": "Turned voice on and unstuck it.",
  "Зняв зависання голосу.": "Unstuck the voice.",
  "Звук чекає натискання кнопки.": "Sound is waiting for a button press.",
  "Голос увімкнув, але браузер ще блокує звук. Натисни кнопку ще раз.": "Voice is on, but the browser still blocks sound. Press the button again.",
  "У цьому вікні немає звуку.": "This window has no sound.",
  "Агент відповів.": "The agent answered.",
  "Агент не відповів.": "The agent did not answer.",
  "Перевірка готова.": "Check is done.",
  "Сховище": "Storage",
  "Голос": "Voice",
  "Стіл": "Desk",
  "читаю мережу…": "reading the network…",
  "жива": "up",
  "немає зв'язку": "no connection",
  "немає слота": "no slot",
  "RPC відмовив": "RPC refused",
  " мс": " ms",
  "слот ": "slot ",
  "Відкрити магазин": "Open the shop",
  "Немає агента. Купіть готового в Магазині.": "No agent yet. Buy a ready one in the Shop.",
  "Тут агент працює сам, у межах лімітів. Немає агента — візьми його в Магазині.": "The agent works on its own, inside the limits. No agent yet — get one in the Shop.",
  "немає": "none",
  "пауза": "paused",
  "події": "events",
  "увімк": "on",
  "читаю": "reading",
  "1 доба": "1 day",
  "2 доби": "2 days",
  "Агенти": "Agents",
  "Боти: ": "Bots: ",
  "Вільно": "Free",
  "Журнал": "Log",
  "Крипто": "Crypto",
  "Куди: ": "To: ",
  "Погода": "Weather",
  "Продаж": "Sell",
  "Профіт": "Profit",
  "Робота": "Job",
  "очікує": "waiting",
  "погода": "weather",
  "працює": "working",
  "стоїть": "idle",
  "читаю…": "reading…",
  "Гаманці": "Wallets",
  "Депозит": "Deposit",
  "Закрито": "Closed",
  "Купівля": "Buy",
  "Кімната": "Room",
  "Профіль": "Profile",
  "Станція": "Station",
  "Сторона": "Side",
  "У ринку": "In market",
  "ще нема": "not yet",
  "Адреса: ": "Address: ",
  "Виведено": "Withdrawn",
  "Вторинка": "Resale",
  "Мережа: ": "Network: ",
  "Резолв: ": "Resolve: ",
  "Сума DCA": "DCA amount",
  "Точність": "Accuracy",
  "У ринках": "In markets",
  "в роботі": "at work",
  "вимкнено": "off",
  "застарів": "stale",
  "створюю…": "creating…",
  " · дельта": " · delta",
  "Бот подій": "Events bot",
  "Надіслати": "Send",
  "Поповнити": "Top up",
  "На касу арбу": "To the arb desk",
  "Каса арбу. Не секретар.": "Arb desk. Not the secretary.",
  "Арбітраж працює сам. Стріляє лише коли є край і каса.": "Arb runs by itself. It fires only when there is an edge and a funded desk.",
  "Нога менша за мінімум біржі.": "The leg is below the exchange minimum.",
  "Немає цієї пари на Backpack.": "Backpack does not list this pair.",
  "Чекаю ціну SOL.": "Waiting for the SOL price.",
  "усі Solana-пари": "all Solana pairs",
  "Читаю книгу Backpack…": "Reading the Backpack book…",
  "Чекаю касу.": "Waiting for the desk.",
  "Край.": "Edge.",
  "Немає кредиту.": "No credit.",
  "Каса Backpack порожня.": "Backpack desk is empty.",
  "Ончейн-каса порожня.": "On-chain desk is empty.",
  "Немає ключа каси ончейн.": "No on-chain desk key.",
  "Зламано, чекає зведення.": "Broken, waiting to square.",
  "Прогнозів": "Forecasts",
  "Скасувати": "Cancel",
  "Сума in: ": "Amount in: ",
  "немає NFT": "no NFT",
  "увімкнено": "on",
  "Крипто-бот": "Crypto bot",
  "Мої токени": "My tokens",
  "сума немає": "no amount",
  "SOL кімнати": "Room SOL",
  "З гаманця: ": "From wallet: ",
  "Підтвердити": "Confirm",
  "безкоштовно": "free",
  "немає цифри": "no figure",
  "читаю USDC…": "reading USDC…",
  " акц. · bid ": " sh. · bid ",
  "SOL на акцію": "SOL per share",
  "USDC кімнати": "Room USDC",
  "Виставити · ": "List · ",
  "Ліміт сесії ": "Session limit ",
  "завантаження": "loading",
  "Готовий агент": "Ready agent",
  "Напиши агенту": "Write to the agent",
  "не підключено": "not connected",
  "створюю ключ…": "creating key…",
  "читаю Devnet…": "reading Devnet…",
  "Вивести Devnet": "Withdraw Devnet",
  "Відкрити Store": "Open Store",
  "Відкрити Працю": "Open Work",
  "Депозит у pUSD": "Deposit to pUSD",
  "Повернути ключ": "Return the key",
  "Статус моста: ": "Bridge status: ",
  "читаю mainnet…": "reading mainnet…",
  "Агент на паузі.": "Agent is paused.",
  "Кімната агентів": "Agent room",
  "Мережа: Mainnet": "Network: Mainnet",
  "Мережа: Polygon": "Network: Polygon",
  "Погасити виграш": "Redeem winnings",
  "Показати секрет": "Show secret",
  "Підтверди угоду": "Confirm the trade",
  "Усього в угодах": "Total in trades",
  "актив не обрано": "no asset picked",
  "створюю адресу…": "creating address…",
  "Адреса кімнати: ": "Room address: ",
  "NFT не підключено": "NFT not connected",
  "Інтервал DCA, сек": "DCA interval, sec",
  "Адреса отримувача": "Recipient address",
  "Взяти і працювати": "Take and work",
  "Дрібні живі угоди": "Small live trades",
  "Очікуваний USDC: ": "Expected USDC: ",
  "Повернути Polygon": "Return Polygon",
  "Сума виводу в SOL": "Withdraw amount in SOL",
  "Phantom підключено": "Phantom connected",
  "Є відкритий ордер.": "There is an open order.",
  "Адреса Polygon 0x…": "Polygon address 0x…",
  "Адресу скопійовано": "Address copied",
  "Вивести SOL агента": "Withdraw agent SOL",
  "Підключити Phantom": "Connect Phantom",
  "немає адреси моста": "no bridge address",
  "читаю котирування…": "reading quote…",
  " pUSD · ціна входу ": " pUSD · entry price ",
  "Jupiter не відповів": "Jupiter did not answer",
  "Відкрити сайт Slice": "Open Slice site",
  "Купити з стратегією": "Buy with strategy",
  "лише комісія мережі": "network fee only",
  "чекає підтвердження": "waiting for confirmation",
  "читаю адресу моста…": "reading bridge address…",
  "Гаманець створюється": "Wallet is being created",
  "Купити ключем агента": "Buy with the agent key",
  "Секрет не відкрився.": "Secret did not open.",
  " · адресу скопійовано": " · address copied",
  "Ключ кімнати · Devnet": "Room key · Devnet",
  "Сума поповнення в SOL": "Top-up amount in SOL",
  "Показати секрет ще раз": "Show secret again",
  "Розрив з Coinbase, bps": "Coinbase gap, bps",
  "Вивести pUSD Polymarket": "Withdraw Polymarket pUSD",
  "Показати секрет Polygon": "Show Polygon secret",
  "Стратегію ще не зчитано": "Strategy not read yet",
  " SOL. Торговий гаманець:": " SOL. Trading wallet:",
  "Гаманця агента ще немає.": "The agent wallet is not here yet.",
  "Записаний секрет Polygon": "Saved Polygon secret",
  "Розумію, що це живий SOL": "I understand this is live SOL",
  "Скасувати ордер у стакані": "Cancel the book order",
  "Поки тихо. Натисніть Work.": "Quiet for now. Press Work.",
  "Вставити секрет Polygon 0x…": "Paste Polygon secret 0x…",
  "Поповни pUSD. Агент стоїть.": "Top up pUSD. The agent is idle.",
  "Соларчик · QuickNode Devnet": "Solarchik · QuickNode Devnet",
  "Секрет Polygon не відкрився.": "Polygon secret did not open.",
  "Архів цієї смуги ще порожній.": "This lane's archive is still empty.",
  "Живий своп Jupiter на mainnet": "Live Jupiter swap on mainnet",
  "Записаний секрет ключа кімнати": "Saved room-key secret",
  "Показати секрет Polygon ще раз": "Show Polygon secret again",
  "Цей токен зараз не веде зміну.": "This token is not on shift right now.",
  " Поповни гаманець. Боти стоять.": " Top up the wallet. Bots are idle.",
  "Вставити записаний секрет ключа": "Paste the saved room-key secret",
  "Створюю ключ на цьому пристрої…": "Creating a key on this device…",
  ". Списує ключ кімнати на Devnet.": ". Charges the room key on Devnet.",
  "Phantom · не підписує живий своп": "Phantom · does not sign the live swap",
  "Агент працює сам у межах лімітів": "The agent works on its own inside the limits",
  "Агент у черзі до наступного вікна.": "The agent is queued for the next window.",
  "Зараз у відкритих ринках порожньо.": "Open markets are empty right now.",
  "Grok ще відповідає. Нову не ставлю.": "Grok is still answering. I am not placing a new one.",
  "Секрет Polygon. Скопіюй сам і сховай.": "Polygon secret. Copy it yourself and hide it.",
  "TWAP 30s немає цифри / 60s немає цифри": "TWAP 30s no figure / 60s no figure",
  "Живий ордер Polymarket CLOB на Polygon": "Live Polymarket CLOB order on Polygon",
  "Кнопка «Поповнити» — лише кран Devnet.": "The Top up button is only the Devnet faucet.",
  "Немає агента. Купіть готового в Store.": "No agent. Buy a ready one in Store.",
  "Live, ще без fill. Продажу акцій немає.": "Live, no fill yet. No share selling.",
  "Поповни торговий гаманець. Боти стоять.": "Top up the trading wallet. Bots are idle.",
  "Секрет ключа кімнати. Скопіюй сам і сховай.": "Room-key secret. Copy it yourself and hide it.",
  "Комісія мінту — Devnet. Mainnet сюди не йде.": "Mint fee is Devnet. Mainnet does not go here.",
  "Ринок порожній. Виставте свого агента з Праці.": "The market is empty. List your agent from Work.",
  "Агент закрив вікно в плюс і стоїть до наступного.": "The agent closed the window in profit and waits for the next one.",
  "Депозит Polymarket Bridge. Solana → pUSD на Polygon": "Polymarket Bridge deposit. Solana → pUSD on Polygon",
  "Торговий гаманець підключено. Живий режим ще вимкнений.": "Trading wallet connected. Live mode is still off.",
  "Ставка в ринку. Агент чекає кінець вікна, щоб закрити її.": "Bet is in the market. The agent waits for the window to end so it can close it.",
  "Газ Polygon цим депозитом може не прийти. Кинь трохи POL на ": "Polygon gas may not arrive with this deposit. Send a little POL to ",
  "Суму виграшу не показую, поки мережа не віддасть новий pUSD.": "I do not show the win amount until the network returns the new pUSD.",
  "Запиши секрет ключа, потім надсилай mainnet SOL на цю адресу.": "Write down the key secret, then send mainnet SOL to this address.",
  "Готовий агент одразу в роботу. Вторинка — токени, які вже виставили.": "A ready agent goes straight to work. Resale is tokens already listed.",
  "Натисни «Показати секрет ще раз». Після цього він з’явиться лише тут.": "Press Show secret again. After that it appears only here.",
  "Це не Jupiter. USDC/SOL з кімнати на цю SVM-адресу стає pUSD на Polygon.": "This is not Jupiter. USDC/SOL from the room to this SVM address becomes pUSD on Polygon.",
  "Без запису секрету ключ зникне разом із браузером. Секрет не йде на сервер.": "Without saving the secret, the key disappears with the browser. The secret does not go to the server.",
  "Купуєте NFT і одразу тиснете Work. Ставки йдуть тестовим SOL цього гаманця.": "You buy the NFT and press Work. Bets use this wallet's test SOL.",
  "Phantom у цьому вікні немає. На Android гаманець Solana відкривається в Chrome. Фейковий конект не ставлю.": "Phantom is not in this window. On Android the Solana wallet opens in Chrome. I do not put a fake connect.",
  "Покупка йде ключем гаманця агента через Jupiter, ті самі акції що на Slice. Сайт Slice окремо не бачить цей ключ.": "The buy uses the agent wallet key through Jupiter, the same shares as on Slice. The Slice site does not see this key.",
  "Гаманець створюється з першого заходу. Біткоїн-бот ставить на 15 хв Up/Down. Події і погода — окремі смуги. У Праці в кожного є огляд і ціль.": "The wallet is created on the first visit. The Bitcoin bot bets 15 min Up/Down. Events and weather are separate lanes. In Work each one has an overview and a goal.",
  "Біткоїн-бот ставить на вікна, які ввімкнені: 5 хв, 15 хв, 1 год, 4 год. Бік вирішує Grok. Купівля лише якщо ask цього боку в коридорі і слот вільний. Події і погода — окремо, від 65%.": "The Bitcoin bot bets the windows that are on: 5 min, 15 min, 1 hour, 4 hours. Grok picks the side. A buy happens only if that side's ask is inside the band and the slot is free. Events and weather are separate, from 65%.",
  "Ключ не розшифрувався": "The key did not decrypt",
  "Ключ Polygon не розшифрувався. Встав записаний секрет.": "The Polygon key did not decrypt. Paste the saved secret.",
  "Секрет Polygon не підійшов. Гаманець не замінив.": "The Polygon secret did not fit. The wallet was not replaced.",
  "контракт створено": "contract created",
  "Поповни гаманець. Боти стоять.": "Top up the wallet. Bots are idle.",
  "Пісочниця. Це тестовий переказ Devnet. Мейннет лише читання": "Sandbox. This is a Devnet test transfer. Mainnet is read-only",
  ", вузол живий": ", node is live",
  "Баланс не вигадую.": "I am not inventing the balance.",
  "Скопіювати ": "Copy ",
  "уже на цьому пристрої. Поповнення і вивід — у шапці.": "is already on this device. Top up and withdraw are in the header.",
  "Крипто 15хв ": "Crypto 15m ",
  "вікно ": "window ",
  " с до резолву": " s to resolve",
  " акц.": " sh.",
  "станція ": "station ",
  "Сесія ": "Session ",
  " · доба ": " · day ",
  "Jupiter (лише читання): близько ": "Jupiter (read only): about ",
  " USDC за ": " USDC for ",
  "Мої агенти": "My agents",
  "Додати агента": "Add an agent",
  "Запустити": "Start",
  "Перформанс": "Performance",
  "Історія угод": "Trade history",
  "Стратегія": "Strategy",
  "Зважений": "Weighted",
  "Чат": "Chat",
  "Епоха": "Epoch",
  "Смуги": "Lanes",
  "Оновити": "Refresh",
  "Кошти в ринках": "Funds in markets",
  "Ончейн · тестовий SOL": "On-chain · test SOL",
  "тільки buy": "buy only",
  "тільки sell": "sell only",
  "buy і sell": "buy and sell",
  "Коридор ask. Поза ним ордера немає.": "Ask band. Outside it there is no order.",
  "Спорт не вмикається. Горизонт резолву:": "Sports stay off. Resolve horizon:",
  "Вікна, на які ставить крипта. Чат міняє той самий список.": "Windows the crypto bot bets. Chat changes the same list.",
  "Ще тихо. Запусти агента — сюди ляжуть ринки, сторона і сума.": "Still quiet. Start the agent — markets, side and size land here.",
  "Кожен відрізок починається з нуля і показує рух PnL закритих угод.": "Each stretch starts at zero and shows closed-trade PnL.",
  "Час поточного вікна. Ставка сидить у ринку, доки вікно не закриється.": "Time left in this window. The bet stays in the market until the window closes.",
  "Розмір угоди залежить від руху ринку, впевненості агента і вільних коштів.": "Size depends on the market move, the agent's confidence and free funds.",
  "Розмір угоди залежить від руху ринку, впевненості агента і вільних коштів. Край і": "Size depends on the market move, the agent's confidence and free funds. Edge and",
  "лишаються помірними.": "stay moderate.",
  "закритих угод.": "closed trades.",
  "Кожен відрізок починається з нуля і показує рух ": "Each stretch starts at zero and shows the move ",
  "серія ": "streak ",
  "вер.": "ver.",
  "Боти:": "Bots:",
  "Сесія": "Session",
  "доба": "day",
  "вікно": "window",
  "Напиши звичайною мовою. Агент міняє смуги, ризик, вікна крипти (5 хв, 15 хв, 1 год, 4 год) і коридор ask. Ставить, якщо прямо попросиш.": "Write in plain language. The agent changes lanes, risk, crypto windows (5 min, 15 min, 1 hour, 4 hours) and the ask band. It bets only if you ask directly.",
  "Вивести з ринку": "Withdraw from the market",
  "Пауза": "Pause",
  "Заблоковано ": "Locked ",
  " SOL до кінця вікна.": " SOL until the window ends.",
  "Мінусів підряд: ": "Losses in a row: ",
  "Увімкни лише смуги цього NFT. Нових ринків тут немає. Робота ": "Turn on only this NFT's lanes. There are no new markets here. Job ",
  "Фʼючерс BTCUSDT, плече 2×, один слот. Це не Jupiter і не Polymarket.": "BTCUSDT futures, 2× leverage, one slot. This is not Jupiter and not Polymarket.",
  "Лише знятий high зі станції в правилах. Це не вимикається.": "Only the recorded high from the station in the rules. This does not turn off.",
  "DEX з Праці не запускається.": "DEX does not start from Work.",
  "Записати стратегію в NFT": "Write the strategy into the NFT",
  "від": "from",
  "до": "to",
  " хв": " min",
  " год": " h",
  "Секрет лишився в браузері.": "The secret stayed in the browser.",
  "Ключ ": "Key ",
  " на пристрої. На Devnet ": " is on this device. On Devnet ",
  " SOL. Вкажи суму й натисни «Поповнити».": " SOL. Type an amount and tap Top up.",
  "Prediction чекає NFT класу 1 або комбо": "Prediction is waiting for a class 1 NFT or a combo",
  "DEX чекає NFT класу 2 або комбо": "DEX is waiting for a class 2 NFT or a combo",
  "СИМУЛЯЦІЯ · devnet, без грошей": "SIMULATION · devnet, no money",
  "Кредит не списується. Mainnet вимкнено на сервері.": "Credit is not spent. Mainnet is off on the server.",
  "Mainnet вимкнено на сервері.": "Mainnet is off on the server.",
  "Каса закрита: немає спільної бази (DATABASE_URL), ліміти не перевірити.": "Desk closed: no shared database (DATABASE_URL), limits cannot be checked.",
  "Mainnet вимкнено: потрібна спільна база (DATABASE_URL).": "Mainnet is off: a shared database (DATABASE_URL) is required.",
  "Mainnet увімкнено на сервері. Ліміт каси 0.02 SOL на добу.": "Mainnet is on at the server. Desk cap 0.02 SOL per day.",
  "Каса закрита: база не відповіла.": "Desk closed: the database did not answer.",
  "Ліміт гаманця: зачекай 30 с або до завтра (UTC).": "Wallet limit: wait 30 s or until tomorrow (UTC).",
  "Ліміт каси: зачекай 30 с або денний ліміт вичерпано.": "Desk limit: wait 30 s, or the daily cap is used up.",
  "Цей NFT не в твоєму гаманці.": "This NFT is not in your wallet.",
  "Арбітраж лише для агента класу 2 або комбо.": "Arbitrage is only for a class 2 agent or a combo.",
  "Не вдалося перевірити NFT ончейн. Спробуй пізніше.": "Could not check the NFT on-chain. Try later.",
  "Цей підпис уже використано.": "This signature was already used.",
  "Підпис застарів. Спробуй ще раз.": "The signature expired. Try again.",
  "Підпис гаманця не збігся.": "The wallet signature did not match.",
  "Немає підпису гаманця.": "No wallet signature.",
  "Немає ключа кімнати.": "No room key.",
  "Не вдалося перевірити гаманець ончейн. Мінт не почато.": "Could not check the wallet on-chain. Mint not started.",
  "Безкоштовний мінт уже йде. Зачекай 10 хв.": "A free mint is already in progress. Wait 10 min.",
  "Сервер не підтвердив безкоштовний мінт. Мінт не почато.": "The server did not confirm the free mint. Mint not started.",
  "Сервер не відповів. Мінт не почато.": "The server did not answer. Mint not started.",
  "Безкоштовний агент уже є. Pro без комісії з прибутку.": "A free agent is already here. Pro takes no cut of profit.",
  "Підключи Phantom або гаманець телефону. Оплата з ключа кімнати не йде.": "Connect Phantom or the phone wallet. The room key does not pay.",
  "Seeker на mainnet. Оплата Pro поки лише Devnet. Нічого не списано.": "Seeker is on mainnet. Pro payment is devnet only for now. Nothing was charged.",
  "Pro · 0% комісії": "Pro · 0% fee",
  "Free · 5% прибутку": "Free · 5% of profit",
  "один безкоштовний на гаманець": "one free mint per wallet",
  "Агент на паузі. Угоду не відправляю.": "Agent is paused. The trade is not sent.",
  "Ліміт угоди": "Trade cap",
  "Денний ліміт": "Daily cap",
  "Ліміт збитків": "Loss cap",
  "Денний мінус": "Daily loss",
  "Угоду не відправляю.": "The trade is not sent.",
  "Комісію не відправлено. Підпис не вигадую.": "The fee was not sent. No signature was invented.",
  "Комісію не відправлено. Немає ключа.": "The fee was not sent. There is no key.",
  "Оплата з твого гаманця на казну…": "Paying the treasury from your wallet…",
  "прийнято. Мінт не пройшов.": "landed. The mint did not.",
  "Ліміти": "Limits",
  "Можна лише нижче стелі. Вище за стелю не ставиться.": "You can only set these lower. The ceiling does not move.",
  "Пауза агента": "Pause the agent",
  "Зняти паузу": "Resume",
  "вікно без комісії": "fee-free window",
  "мінус, комісії немає": "a loss, no fee",
  "папір, не відправлено": "paper, not sent",
  "Кредит": "Credit",
  "Каса закрита.": "Desk closed.",
  "MAINNET · Кредит": "MAINNET · Credit",
  "пара": "pair",
  "ончейн": "on-chain",
  "пар ·": "pairs ·",
  "Події · Grok від 65% · ставка": "Events · Grok from 65% · stake",
  "Біткоїн": "Bitcoin",
  "· край": "· edge",
  "bps · ставка": "bps · stake",
  "обидва": "both",
  "· поріг": "· threshold",
  "с · усі Solana-пари": "s · all Solana pairs",
  "серія": "streak",
  "відправлено": "sent",
  "не відправлено": "not sent",
  "· комісія": "· fee",
  "· звірено сервером": "· verified by server",
  "· не звірено:": "· not verified:",
  "· чекає звірки": "· awaiting verification",
  "Угода, SOL (стеля": "Trade, SOL (cap",
  "Доба, SOL (стеля": "Day, SOL (cap",
  "Мінусів підряд (стеля": "Losses in a row (cap",
  "Денний мінус, SOL (стеля": "Day loss, SOL (cap",
  "слот": "slot",
  "мс · жива": "ms · live",
  "A · Backpack дешевше": "A · Backpack cheaper",
  "B · Titan дешевше": "B · Titan cheaper",
  "Обидва боки": "Both sides",
  "Цей NFT старий: він не з колекції сервера, тому арбітраж його не приймає. Перенос створить копію з тими самими стратегією і статистикою, а старий спалить. Без підпису оплати буде Free (один на гаманець). Для Pro встав підпис оплати 0.1 SOL.": "This NFT is old: it is not in the server collection, so arbitrage refuses it. Moving creates a copy with the same strategy and stats and burns the old one. Without a payment signature it becomes Free (one per wallet). For Pro, paste the 0.1 SOL payment signature.",
  "Підпис оплати Pro (необов'язково)": "Pro payment signature (optional)",
  "Перенести в колекцію сервера": "Move to server collection",
  "Готові варіанти. Натисни, перевір числа і запиши.": "Presets. Tap one, check the numbers and save.",
  "Пауза, сек": "Pause, sec",
  "Розмір, SOL": "Size, SOL",
  "Поріг чистого краю, bps": "Net edge threshold, bps",
  "Варіант": "Variant",
  "A · купити на Backpack": "A · buy on Backpack",
  "B · купити через Titan": "B · buy via Titan",
  "вже на столі, можна замінити": "already on the desk, can be replaced",
  "Бот читає ці числа: варіант, поріг, розмір, паузу. Котирування Titan на цей розмір. Чистий край уже без 0,10% Backpack і 5 bps запасу. Ордер не йде, поки каса Backpack порожня.": "The bot reads these numbers: variant, threshold, size, pause. Titan quotes this size. Net edge already excludes Backpack's 0.10% and a 5 bps buffer. No order goes out while the Backpack desk is empty.",
  "Сума на касу арбу": "Amount for the arb desk",
  "Розділи столу": "Desk sections",
  "Скопіюйте адресу": "Copy the address",
  "с": "s",
  "д": "d",
  "Відкрита BUY": "Open BUY",
  "акц.": "sh.",
  "акц. · bid": "sh. · bid",
  "Газ Polygon цим депозитом може не прийти. Кинь трохи POL на": "Polygon gas may not arrive with this deposit. Send a little POL to",
  "Статус моста:": "Bridge status:",
  " · невідомий мінімум": " · unknown minimum",
  "· вхід": "· entry",
  "pUSD · ціна входу": "pUSD · entry price",
  "Резолв:": "Resolves:",
  "· дельта": "· delta",
  "с до резолву": "s to resolve",
  "· резолв TWAP": "· TWAP resolve",
  "станція": "station",
  "Адреса:": "Address:",
  "Jupiter (лише читання): близько": "Jupiter (read only): about",
  "USDC за": "USDC for",
  "Сума in:": "Amount in:",
  "Очікуваний USDC:": "Expected USDC:",
  "Адреса кімнати:": "Room address:",
  "Мережа:": "Network:",
  "З гаманця:": "From wallet:",
  "Куди:": "To:",
  "Ліміт сесії": "Session limit",
  "SOL. Торговий гаманець:": "SOL. Trading wallet:",
  "Клас": "Class",
  "Ключ": "Key",
  "Виставити ·": "Place ·",
  "Крипто 15хв": "Crypto 15m",
  "Немає NFT агента.": "No agent NFT.",
  "Цей NFT не з колекції сервера. Перенеси його кнопкою «Перенести в колекцію сервера».": "This NFT is not in the server collection. Move it with «Move to server collection».",
  "Кредит арбу": "Arb credit",
  "SOL. Треба від": "SOL. Needs at least",
  "Немає підпису оплати Pro.": "No Pro payment signature.",
  "Не вдалося перевірити оплату на Devnet. Спробуй ще раз.": "Could not check the payment on Devnet. Try again.",
  "Безкоштовний агент уже є.": "You already have a free agent.",
  "Цю оплату вже використано.": "This payment was already used.",
  "Сервер не зібрав мінт:": "Server could not build the mint:",
  "Немає такого агента.": "No such agent.",
  "Перенос закрито: на сервері немає ключа мінту.": "Move closed: the server has no mint key.",
  "Сервер не відповів.": "Server did not answer.",
  "Не вдалося прочитати NFT ончейн.": "Could not read the NFT on-chain.",
  "Цей NFT уже в колекції сервера.": "This NFT is already in the server collection.",
  "Це не агент Solarchik.": "This is not a Solarchik agent.",
  "Безкоштовний агент уже є. Для Pro додай підпис оплати Pro.": "You already have a free agent. For Pro, add the Pro payment signature.",
  "Не вдалося перевірити гаманець ончейн.": "Could not check the wallet on-chain.",
  "Немає NFT.": "No NFT.",
  "Кредит арбу закритий: немає бази (DATABASE_URL).": "Arb credit closed: no database (DATABASE_URL).",
  "База не відповіла.": "Database did not answer.",
  "Погані дані.": "Bad data.",
  "Кредит арбу закритий: немає бази (DATABASE_URL). Нічого не зараховано.": "Arb credit closed: no database (DATABASE_URL). Nothing credited.",
  "Mainnet не відповів. Спробуй ще раз.": "Mainnet did not answer. Try again.",
  "Цю транзакцію вже зараховано.": "This transaction was already credited.",
  "База не відповіла. Спробуй ще раз.": "Database did not answer. Try again.",
  "Немає бази: комісію не звірено.": "No database: fee not verified.",
  "Devnet не відповів.": "Devnet did not answer.",
  "Цей підпис або рядок уже звірено з іншою транзакцією.": "This signature or row was already matched to another transaction.",
  "Сервер підписує мінт.": "Server signs the mint.",
  "Dev: ключа мінту немає, мінт з браузера.": "Dev: no mint key, mint from the browser.",
  "Pro закрито: на сервері немає ключа мінту (MINT_AUTHORITY_SECRET). Нічого не списано.": "Pro closed: the server has no mint key (MINT_AUTHORITY_SECRET). Nothing charged.",
  "Free закрито: на сервері немає ні ключа мінту, ні бази. Нічого не списано.": "Free closed: the server has neither a mint key nor a database. Nothing charged.",
  "Ключа мінту немає. Free перевіряє сервер ончейн.": "No mint key. The server checks Free on-chain.",
  "Оплату не знайдено на Devnet. Зачекай підтвердження і спробуй ще раз.": "Payment not found on Devnet. Wait for confirmation and try again.",
  "Оплата впала з помилкою.": "Payment failed with an error.",
  "Оплата ще не в блоці.": "Payment is not in a block yet.",
  "Оплата застара для нового мінту.": "Payment is too old for a new mint.",
  "У транзакції немає переказу": "The transaction has no transfer of",
  "SOL на казну.": "SOL to the treasury.",
  "Оплата не прив'язана до цього гаманця кімнати.": "Payment is not tied to this room wallet.",
  "Транзакцію не знайдено. Зачекай підтвердження і спробуй ще раз.": "Transaction not found. Wait for confirmation and try again.",
  "Транзакція впала з помилкою.": "Transaction failed with an error.",
  "Транзакція ще не в блоці.": "Transaction is not in a block yet.",
  "Транзакція застара.": "Transaction is too old.",
  "У транзакції немає мемо з адресою NFT.": "The transaction has no memo with the NFT address.",
  "Немає переказу від 0.005 SOL з гаманця кімнати на касу арбу.": "No transfer of at least 0.005 SOL from the room wallet to the arb desk.",
  "Переказ більший за 0.02 SOL. Кредит не зараховано.": "Transfer is above 0.02 SOL. Credit not added.",
  "Сума комісії поза межами.": "Fee amount out of range.",
  "У транзакції немає мемо цієї комісії.": "The transaction has no memo for this fee.",
  "Немає переказу цієї суми з гаманця кімнати на казну.": "No transfer of this amount from the room wallet to the treasury.",
  "Наступний розбір подій через": "Next events review in",
  "хв.": "min.",
  "Уже є крипто-нога. Нову не ставлю.": "A crypto leg is already open. Not placing a new one.",
  "Зарано. Чекаю кінець вікна. Ордера немає.": "Too early. Waiting for the window end. No order.",
  "Дельта в шумі. Ордера немає.": "Delta is within noise. No order.",
  "Немає свіжого Chainlink TWAP. Ордера немає.": "No fresh Chainlink TWAP. No order.",
  "Край після ціни замалий. Ордера немає.": "Edge after price is too small. No order.",
  "Прогноз проти дельти. Ордера немає.": "Forecast goes against the delta. No order.",
  "крипто": "crypto",
  "ціна входу": "entry price",
  "Транзакція не пройшла": "Transaction failed",
  "Кран Devnet відповів відмовою: ліміт на сьогодні. Кнопка стукала в мережу, SOL не зараховано.": "The Devnet faucet refused: daily limit reached. The request reached the network, no SOL credited.",
  "На Devnet у цього гаманця немає SOL. Транзакцію не відправив. Капни кран на faucet.solana.com на адресу кімнати.": "This wallet has no SOL on Devnet. Transaction not sent. Use faucet.solana.com on the room address.",
  "На Devnet у": "On Devnet,",
  "зараз 0 SOL. Цифра зі старого ланцюга не рахується. Капни devnet SOL на faucet.solana.com на цю адресу.": "has 0 SOL now. The number from the old chain does not count. Get devnet SOL from faucet.solana.com to this address.",
  "Мало тестового SOL. Є": "Not enough test SOL. Have",
  ", потрібно": ", need",
  "+ комісія.": "+ fee.",
  "більше не ставить": "no longer places",
  "Ліміт Grok оновлено. Ще 6 запитів.": "Grok limit reset. 6 more requests.",
  "Сервер не відповів. Спробую ще раз пізніше.": "Server did not answer. Will try again later.",
  "DEX-переказ": "DEX transfer",
  "Це тестовий переказ Devnet.": "This is a Devnet test transfer.",
  "Закрити ставку": "Close position",
  "Повернути": "Return",
  "Мінус": "Loss",
  "SOL. Виплати немає.": "SOL. No payout.",
  "Ставка": "Position",
  ". Мережа так і не підтвердила. Баланс не оновлюю.": ". The network never confirmed. Balance not updated.",
  "Mainnet відхилив транзакцію.": "Mainnet rejected the transaction.",
  "Два мінуси підряд. Боти стоять.": "Two losses in a row. Bots stopped.",
  "Розбір обірвався. Натисни ще раз.": "Review was cut off. Tap again.",
  "Спочатку погасити виграш. Нову не ставлю.": "Redeem the win first. Not placing a new one.",
  "Редіму немає.": "Nothing to redeem.",
  "Ставка закрита. Слот вільний.": "Position closed. Slot is free.",
  "Спочатку обидві галочки живого режиму. Ордера немає.": "Tick both live-mode boxes first. No order.",
  "Ордер ще в стакані. Продажу акцій немає.": "Order is still in the book. No share sale.",
  "CLOB не скасував. Слот лишається.": "CLOB did not cancel. Slot stays taken.",
  "Ордер скасовано в стакані.": "Order cancelled in the book.",
  "Ордер скасовано. Слоту немає.": "Order cancelled. No slot held.",
  "Ордер у стакані. Ще не скасовую.": "Order is in the book. Not cancelling yet.",
  "Немає статусу ордера. Продажу немає.": "No order status. No sale.",
  "Питаю Grok, чи закривати.": "Asking Grok whether to close.",
  "Авто вимкнено. Нових угод немає.": "Auto is off. No new trades.",
  "Grok не зібрав рішення.": "Grok did not produce a decision.",
  "Живий ордер Polymarket CLOB на Polygon. Чекає підтвердження.": "Live Polymarket CLOB order on Polygon. Waiting for confirmation.",
  "Живий ордер Polymarket CLOB SELL": "Live Polymarket CLOB SELL order",
  "Макс. на угоду 0.005 SOL. Угоду не відправляю.": "Max per trade 0.005 SOL. Trade not sent.",
  "Поповни SOL. Агент стоїть.": "Top up SOL. Agent is idle.",
  "Ліміт доби 0.02 SOL. Угоду не відправляю.": "Daily limit 0.02 SOL. Trade not sent.",
  "Уже є відкрита угода. Нову не ставлю.": "A trade is already open. Not placing a new one.",
  "Спочатку закрити відкриту ставку. Нову не ставлю.": "Close the open position first. Not placing a new one.",
  "Читаю ринок і питаю Grok.": "Reading the market and asking Grok.",
  "Мінімум ставки 1 pUSD. Поповни. Ордера немає.": "Minimum stake is 1 pUSD. Top up. No order.",
  "Живий ордер Polymarket CLOB": "Live Polymarket CLOB order",
  "ключ кімнати": "room key",
  "ринок кімнати": "room market",
  "Макс. на угоду 0.02 SOL. Угоду не відправляю.": "Max per trade 0.02 SOL. Trade not sent.",
  "Ліміт доби 0.3 SOL. Угоду не відправляю.": "Daily limit 0.3 SOL. Trade not sent.",
  "Мало тестового SOL для переказу": "Not enough test SOL for the transfer",
  "RIG закрив вікно в мінус. Ставка лишилась на ринку.": "RIG closed the window at a loss. The stake stayed in the market.",
  "RIG мінус": "RIG loss",
  "· без виплати": "· no payout",
  "Тестовий переказ Devnet": "Devnet test transfer",
  "RIG повернув кошти ·": "RIG returned funds ·",
  "Ключ кімнати не підписав. Нічого не відправлено.": "Room key did not sign. Nothing sent.",
  "SOL · ключ кімнати ·": "SOL · room key ·",
  ". Мережа ще не підтвердила. Баланс не оновлюю.": ". The network has not confirmed yet. Balance not updated.",
  "Mainnet не прийняв транзакцію.": "Mainnet did not accept the transaction.",
  "Гаманець кімнати ще не готовий.": "Room wallet is not ready yet.",
  "Живий режим увімкнено. Ще потрібна згода на живий SOL.": "Live mode on. Consent to live SOL is still needed.",
  "Пісочниця Devnet.": "Devnet sandbox.",
  "Спочатку ввімкни дрібні живі угоди.": "Turn on small live trades first.",
  "не розшифрувався": "could not be decrypted",
  "Ключ кімнати повернуто:": "Room key restored:",
  "Секрет не підійшов. Ключ не замінив.": "Secret did not match. Key not replaced.",
  "Гаманець Polygon повернуто:": "Polygon wallet restored:",
  "Нічого не відправлено.": "Nothing sent.",
  "Підтверджено. Шлю тестову транзакцію Devnet.": "Confirmed. Sending a Devnet test transaction.",
  "Угоду скасовано. Нічого не відправлено.": "Trade cancelled. Nothing sent.",
  "Ордер скасовано. Нічого не відправлено.": "Order cancelled. Nothing sent.",
  "Живий шлях вимкнений. Нічого не відправлено.": "Live path is off. Nothing sent.",
  "Скасовую ордер у стакані.": "Cancelling the order in the book.",
  "CLOB не відповів": "CLOB did not answer",
  "Депозит скасовано. Нічого не відправлено.": "Deposit cancelled. Nothing sent.",
  "немає котирування": "no quote",
  ". Кошти ще не completed. Баланс не вигадую.": ". Funds not completed yet. Not inventing a balance.",
  ". Кошти ще не completed.": ". Funds not completed yet.",
  "Смуга вимкнена на NFT. Ордера немає.": "This lane is off on the NFT. No order.",
  "погоду": "weather",
  "Читаю": "Reading",
  "і питаю Grok.": "and asking Grok.",
  "Уже є ця ставка. Ордера немає.": "This position already exists. No order.",
  "Підписую ключем Polygon.": "Signing with the Polygon key.",
  "Grok не зібрав рішення. Нічого не відправлено.": "Grok did not produce a decision. Nothing sent.",
  "Немає відкритої позиції. Закриття немає.": "No open position. Nothing to close.",
  "уже на пристрої. На Devnet": "is already on this device. On Devnet",
  "SOL — вкажи суму й натисни «Поповнити».": "SOL — enter an amount and tap «Top up».",
  "на пристрої. На Devnet": "on this device. On Devnet",
  "SOL. Вкажи суму й натисни «Поповнити».": "SOL. Enter an amount and tap «Top up».",
  "Ще йде транзакція. Зачекайте.": "A transaction is still running. Please wait.",
  "Вкажи суму в SOL.": "Enter an amount in SOL.",
  "За один раз кран бере до 100 тестових SOL.": "The faucet gives up to 100 test SOL at a time.",
  "Немає ключа": "No key",
  "Прошу": "Requesting",
  "SOL у крана Devnet…": "SOL from the Devnet faucet…",
  "Кран підтвердив": "Faucet confirmed",
  "…. Зараз": "…. Now",
  "Поповнення": "Top-up",
  "Збираю весь mainnet SOL…": "Collecting all mainnet SOL…",
  "Підпис пішов, мережа ще не підтвердила ·": "Signature sent, network has not confirmed yet ·",
  "Ключ агента не підписав. Нічого не відправлено.": "Agent key did not sign. Nothing sent.",
  "Виводжу SOL з гаманця агента…": "Withdrawing SOL from the agent wallet…",
  "Вивід": "Withdrawal",
  "SOL з гаманця агента ·": "SOL from the agent wallet ·",
  "Вивід mainnet": "Mainnet withdrawal",
  "Немає NFT арбітражу на цьому ключі.": "No arbitrage NFT on this key.",
  "Шлю SOL на касу арбу…": "Sending SOL to the arb desk…",
  "Переказ": "Transfer",
  "… пішов. Кредит не зараховано:": "… sent. Credit not added:",
  "Підпис пішов, кредит зарахую після підтвердження ·": "Signature sent, credit will be added after confirmation ·",
  "Каса арбу": "Arb desk",
  "Виводжу pUSD з гаманця Polymarket…": "Withdrawing pUSD from the Polymarket wallet…",
  "Вивід pUSD ·": "pUSD withdrawal ·",
  "Ключ агента не підписав. Покупки немає.": "Agent key did not sign. No purchase.",
  "Купую акцію ключем агента…": "Buying the share with the agent key…",
  "куплено ключем агента ·": "bought with the agent key ·",
  "Адреса отримувача не схожа на ключ Solana.": "Recipient address does not look like a Solana key.",
  "Це адреса цього ж гаманця. Вивід скасовано.": "That is this same wallet. Withdrawal cancelled.",
  "Сума виводу має бути більша за нуль.": "Withdrawal amount must be above zero.",
  "Мало SOL для виводу. Є": "Not enough SOL to withdraw. Have",
  ", треба": ", need",
  "плюс": "plus",
  "на комісію.": "for the fee.",
  "Виводжу": "Withdrawing",
  "SOL на": "SOL to",
  "Вивід підтверджено": "Withdrawal confirmed",
  "…. Залишок": "…. Remaining",
  "Немає цього NFT або ключа кімнати.": "This NFT or the room key is missing.",
  "Сервер готує перенос у свою колекцію…": "Server is preparing the move into its collection…",
  "Нічого не змінено.": "Nothing changed.",
  "у колекції сервера. Старий NFT спалено.": "is in the server collection. Old NFT burned.",
  "у колекції сервера. Старий NFT не спалився — він більше не працює на арбі.": "is in the server collection. Old NFT was not burned — it no longer works for arbitrage.",
  "Перенос": "Move",
  "Перенос не пройшов.": "Move failed.",
  "Сервер мінту не відповів. Нічого не списано.": "Mint server did not answer. Nothing charged.",
  "Поповни Devnet краном. Для мінту треба 0.02 SOL.": "Top up Devnet from the faucet. Minting needs 0.02 SOL.",
  "Сервер перевіряє право на мінт…": "Server is checking mint eligibility…",
  "Сервер мінту не відповів.": "Mint server did not answer.",
  "Оплату": "Payment",
  "… збережено, повтори мінт.": "… saved, retry the mint.",
  "Мінт не почато.": "Mint not started.",
  "Мінчу агента в Core…": "Minting the agent in Core…",
  "Мінчу агента. Списується лише комісія мережі…": "Minting the agent. Only the network fee is charged…",
  "у гаманці.": "is in the wallet.",
  ". Оплата": ". Payment",
  ". Лише комісія мережі.": ". Network fee only.",
  "Читаю стратегію з токена…": "Reading the strategy from the token…",
  "Агент уже в кімнаті.": "Agent is already in the room.",
  "Зупинено. Пишу атрибути в Core…": "Stopped. Writing attributes to Core…",
  "Зміну зупинено. Стратегія йде в NFT.": "Shift stopped. Strategy goes into the NFT.",
  "Core оновлено": "Core updated",
  "NFT зник з гаманця": "NFT left the wallet",
  "Grok розбирає ринок…": "Grok is reviewing the market…",
  "Grok не відповів. Ставку не відкриваю.": "Grok did not answer. Not opening a position.",
  "Стратегію оновлено. Вікно пішло спочатку.": "Strategy updated. Window restarted.",
  "Пишу стратегію в Core…": "Writing the strategy to Core…",
  "Стратегію записано в токен": "Strategy written to the token",
  "Цей токен веде зміну.": "This token runs the shift.",
  "працює. Вікно пішло спочатку.": "is working. Window restarted.",
  "Пауза. Вікно заморожено.": "Paused. Window frozen.",
  "Агента поставлено на паузу.": "Agent paused.",
  "У ринках нічого не заблоковано.": "Nothing is locked in markets.",
  "Повертаю кошти з ринку…": "Returning funds from the market…",
  "Ринок не повернув ставку.": "The market did not return the stake.",
  "Кошти з ринку повернуто ·": "Funds returned from the market ·",
  "Напиши агенту, що змінити.": "Tell the agent what to change.",
  "Агент ще відповідає.": "Agent is still replying.",
  "Немає цього агента.": "This agent is missing.",
  "Агент ставить за проханням з чату.": "Agent trades per the chat request.",
  "Агент переписав стратегію з чату.": "Agent rewrote the strategy from chat.",
  "· токен": "· token",
  "Переказ NFT на касу ринку…": "Transferring the NFT to the market desk…",
  "на ринку за": "listed for",
  "тестових SOL.": "test SOL.",
  "→ каса.": "→ desk.",
  "Купівля: SOL продавцю, NFT назад у гаманець…": "Buying: SOL to the seller, NFT back to the wallet…",
  "Куплено": "Bought",
  "Транзакція відхилена": "Transaction rejected",
  "Транзакція не підтвердилась": "Transaction did not confirm",
  "кран відмовив": "faucet refused",
  "Сума поповнення нульова": "Top-up amount is zero",
  "Кран Devnet не видав SOL на": "The Devnet faucet gave no SOL to",
  "0 SOL. Натисни «Поповнити» або капни кран на faucet.solana.com.": "0 SOL. Tap «Top up» or use faucet.solana.com.",
  "замало SOL. Натисни «Поповнити» ще раз.": "not enough SOL. Tap «Top up» again.",
  "Core asset не знайдено": "Core asset not found",
  "У NFT немає адреси колекції Core": "The NFT has no Core collection address",
  "NFT не в цьому гаманці": "NFT is not in this wallet",
  "Core asset без колекції": "Core asset without a collection",
  "Мало тестового SOL для ставки RIG": "Not enough test SOL for the RIG stake",
  "На ринку каси замало, щоб повернути ставку. Спробуй ще раз.": "The market desk is too low to return the stake. Try again.",
  "Агент не відповів. Спробуй ще раз.": "Agent did not answer. Try again.",
  "Стіл не завантажився. Онови сторінку": "Desk did not load. Reload the page",
  "Phantom: підключення відхилено. Нічого не змінено.": "Phantom: connection declined. Nothing changed.",
  "Phantom не підключився. Нічого не змінено.": "Phantom did not connect. Nothing changed.",
  "Покупка не пройшла": "Purchase failed",
  "Комісію не відправлено. Ключ або модуль мережі не відкрився.": "Fee not sent. The key or network module did not open.",
  "Гаманець кімнати не відкрився. Онови сторінку.": "Room wallet did not open. Reload the page.",
  "Ця оплата не схожа на оплату саме цього NFT (мінт мав бути до 30 хв після оплати).": "This payment does not look like the payment for this NFT (the mint had to follow within 30 min).",
  "Це не схоже на підпис транзакції Solana.": "This does not look like a Solana transaction signature.",
  "Сервер читає переказ на mainnet…": "Server is reading the transfer on mainnet…",
  "Кредит зараховано. Зараз": "Credit added. Now",
  "Кредит не зараховано:": "Credit not added:",
  "Підпис старого поповнення": "Signature of an earlier deposit",
  "Зарахувати переказ": "Credit this transfer",
  "% · тейк": "% · take",
  "(deny) забороняє цю угоду.": "(deny) forbids this trade.",
  "Продаж через": "Sale in",
  "замок": "lock",
  "Стоп від 1 до 100 % ставки (ціле).": "Stop from 1 to 100 % of stake (integer).",
  "Перевага (edge) від 0 до 500 bps.": "Edge from 0 to 500 bps.",
  "Тейк від 1 до 500 % ставки (ціле).": "Take from 1 to 500 % of stake (integer).",
  "deny без умови заборонить усе.": "deny without a condition forbids everything.",
  "lane = crypto, events або weather.": "lane = crypto, events or weather.",
  "готово": "done",
  "для lane лише = або !=.": "lane takes only = or !=.",
  "не розібрав «": "could not parse «",
  "почни з allow або deny (allow yes if price < 0.4).": "start with allow or deny (allow yes if price < 0.4).",
  "почни з allow або deny (allow yes if price": "start with allow or deny (allow yes if price",
  "Коридор ціни: 0.05 ≤ від": "Price band: 0.05 ≤ from",
  "APR від зміни": "APR since change",
  "DEX-агент не має стратегії прогнозів.": "A DEX agent has no prediction strategy.",
  "Devnet не відповів. Спробуй ще раз.": "Devnet did not answer. Try again.",
  "NFT виставлено на продаж. Спершу зніми з продажу.": "The NFT is listed. Unlist it first.",
  "NFT заморожено чужим делегатом.": "The NFT is frozen by another delegate.",
  "NFT не з колекції сервера: спершу перенеси його (кнопка «Перенести»).": "The NFT is not in the server collection: move it first (the «Move» button).",
  "NFT не заморожено під лістинг.": "The NFT is not frozen for the listing.",
  "NFT не заморожено під сервером: замок продажу не стоїть.": "The NFT is not frozen under the server: the sale lock is not set.",
  "NFT не знайдено на Devnet.": "NFT not found on Devnet.",
  "NFT не читається.": "Cannot read the NFT.",
  "NFT ще в продавця.": "The NFT is still with the seller.",
  "SOL · коридор": "SOL · band",
  "SOL зі стратегії.": "SOL from the strategy.",
  "SOL: цього досить.": "SOL: that is enough.",
  "Strategy NFT · стратегія на ланцюгу (devnet)": "Strategy NFT · on-chain strategy (devnet)",
  "tx результатів": "results tx",
  "· вікна": "· windows",
  "· ставка ≤": "· stake ≤",
  "Атрибути Core (devnet)": "Core attributes (devnet)",
  "Атрибути NFT під чужим ключем.": "The NFT attributes are under another key.",
  "Виставити, SOL": "List, SOL",
  "Виставлено": "Listed",
  "Виставляю NFT (ескроу на сервері)…": "Listing the NFT (server escrow)…",
  "Власник": "Owner",
  "Вікна, хв": "Windows, min",
  "Вікно": "Window",
  "Готовий агент одразу в роботу. Ринок — Strategy NFT, які вже виставили (devnet SOL, ескроу сервера, 5% роялті).": "A ready agent goes to work at once. Market: Strategy NFTs already listed (devnet SOL, server escrow, 5% royalty).",
  "Графік PnL з’явиться після 2 закритих угод.": "The PnL chart appears after 2 closed trades.",
  "Для суддів · лише devnet": "For judges · devnet only",
  "Демо Strategy NFT на devnet": "Demo Strategy NFTs on devnet",
  "Колекція": "Collection",
  "продавець": "seller",
  "мінт": "mint",
  "замок до": "lock until",
  "замок знято": "lock released",
  "зміна стратегії": "strategy change",
  "переказ відхилено ланцюгом": "transfer refused by the chain",
  "запис результатів": "results write",
  "Ескроу зламано (NFT рушив). Лістинг знято.": "Escrow broken (the NFT moved). Listing removed.",
  "Жодне правило allow не підходить.": "No allow rule matches.",
  "Замок продажу ще": "Sale lock still",
  "Замок продажу ще діє після зміни стратегії.": "The sale lock after the strategy change is still on.",
  "Записано": "Written",
  "Записати в NFT": "Write to NFT",
  "Змінено": "Changed",
  "Зміни стратегії:": "Strategy changes:",
  "Зняти з продажу": "Unlist",
  "Знято з продажу": "Unlisted",
  "Коридор ціни від": "Price band from",
  "Коридор ціни до": "Price band to",
  "Кран лише для devnet.": "The faucet is devnet only.",
  "Кран сервера": "Server faucet",
  "Кран сервера на сьогодні вичерпано.": "The server faucet is used up for today.",
  "Кран сервера надіслав": "Server faucet sent",
  "Кран сервера не відправив SOL.": "The server faucet did not send SOL.",
  "Кран сервера не налаштований (FAUCET_SECRET).": "The server faucet is not set up (FAUCET_SECRET).",
  "Кран сервера:": "Server faucet:",
  "Купити": "Buy",
  "Купую…": "Buying…",
  "Купівлю не підтверджено.": "Purchase not confirmed.",
  "Ланцюг ще не показав зміну.": "The chain does not show the change yet.",
  "Ланцюг ще не показує ескроу (заморозка + делегат переказу).": "The chain does not show the escrow yet (freeze + transfer delegate).",
  "Ліміт крана для цієї мережі на сьогодні.": "Faucet limit for this network today.",
  "Лістинг не активний.": "The listing is not active.",
  "Лістинг не підтверджено.": "Listing not confirmed.",
  "Лістингів немає. Свій NFT можна виставити через": "No listings. You can list your NFT",
  "Магазин → «Агенти»: візьми Free агента (мінт на devnet).": "Store → «Agents»: take a Free agent (devnet mint).",
  "Магазин → «Ринок»: купи виставлений Strategy NFT; свій можна виставити після замка.": "Store → «Market»: buy a listed Strategy NFT; yours can be listed after the lock.",
  "На кожній картці: посилання Explorer і «Перевірити APR».": "Every card: Explorer links and «Verify APR».",
  "На сервері немає ключа мінту (MINT_AUTHORITY_SECRET).": "The server has no mint key (MINT_AUTHORITY_SECRET).",
  "Не більше": "At most",
  "Не вийшло.": "Did not work.",
  "Не за стратегією NFT:": "Not by the NFT strategy:",
  "Немає бази (DATABASE_URL): сервер не веде стратегії.": "No database (DATABASE_URL): the server keeps no strategies.",
  "Немає бази або ключа мінту.": "No database or mint key.",
  "Немає бази: кран вимкнено.": "No database: faucet off.",
  "Немає лістингу.": "No listing.",
  "Немає твого лістингу.": "You have no listing.",
  "Немає ціни.": "No price.",
  "Отримати devnet SOL": "Get devnet SOL",
  "Параметри й хеш живуть в атрибутах Core цього NFT. Сервер перевіряє правила й підписує запис; угоди поза стратегією сервер не приймає. Кожна зміна ставить замок продажу на": "Params and hash live in this NFT's Core attributes. The server validates the rules and signs the write; it rejects trades outside the strategy. Every change sets a sale lock of",
  "Перевага, bps (0–500)": "Edge, bps (0–500)",
  "Перевірити": "Verify",
  "Перевірити APR": "Verify APR",
  "Пишу…": "Writing…",
  "Повний прохід лише для крону.": "Full pass is for the cron only.",
  "Погана адреса NFT.": "Bad NFT address.",
  "Погана стратегія.": "Bad strategy.",
  "Правила (до 6, через «;»): allow|deny [yes|no] if price|hour|window|lane|stake &lt; &gt; = значення": "Rules (up to 6, split by «;»): allow|deny [yes|no] if price|hour|window|lane|stake &lt; &gt; = value",
  "Правила довші за": "Rules longer than",
  "Правило": "Rule",
  "Праця → «Strategy NFT»: зміни стратегію й запиши в NFT (замок продажу": "Work → «Strategy NFT»: change the strategy and write it to the NFT (sale lock",
  "Продавець не передав серверу право переказу (лістинг не активний).": "The seller did not give the server the transfer right (listing not active).",
  "Продаж з": "Sale from",
  "Продажі:": "Sales:",
  "Публічний кран Devnet зайнятий. Прошу кран сервера…": "Public Devnet faucet is busy. Asking the server faucet…",
  "Результат": "Results",
  "Ризик": "Risk",
  "Ринок": "Market",
  "Ринок Strategy NFT на devnet. Ціна в devnet SOL; 95% продавцю, 5% роялті в скарбницю — одна атомарна транзакція. NFT на час лістингу заморожений сервером, тож продавець не може його вивести. Кожну картку можна перевірити в Explorer і кнопкою «Перевірити APR».": "Strategy NFT market on devnet. Price in devnet SOL; 95% to the seller, 5% royalty to the treasury, in one atomic transaction. While listed the NFT is frozen by the server, so the seller cannot move it. Every card can be checked in Explorer and with «Verify APR».",
  "Розбіжності:": "Mismatches:",
  "Сервер не зібрав купівлю:": "The server could not build the purchase:",
  "Сервер не зібрав лістинг:": "The server could not build the listing:",
  "Сервер не зібрав транзакцію:": "The server could not build the transaction:",
  "Сервер не прочитав ринок.": "The server could not read the market.",
  "Сервер не підписував цю версію.": "The server did not sign this version.",
  "Сервер не підтвердив стратегію.": "The server did not confirm the strategy.",
  "Симуляція: ці угоди агент робить у браузері, SOL на ставку не рухається. Сервер сам читає ціну Polymarket на вході й виході та час. Справжні транзакції тут: запис стратегії й результатів у NFT, комісії Free та продажі.": "Simulated: the agent makes these trades in the browser; no SOL moves for the stake. The server reads the Polymarket price at entry and exit and the time itself. Real transactions here: strategy and results writes to the NFT, Free fees and sales.",
  "Смуга": "Lane",
  "Смуги: crypto, events, weather (хоч одна, без повторів).": "Lanes: crypto, events, weather (at least one, no repeats).",
  "Справжніх грошей тут немає. Гаманець кімнати створюється в браузері автоматично. Одна кнопка дає тестові SOL: спершу публічний кран devnet, а якщо він на ліміті — кран сервера (раз на добу на гаманець).": "No real money here. The room wallet is created in the browser automatically. One button gets test SOL: first the public devnet faucet, and if it is rate-limited, the server faucet (once a day per wallet).",
  "Стоп-лосс, % (1–100)": "Stop-loss, % (1–100)",
  "Стратегію записано": "Strategy written",
  "Стратегію записано в NFT": "Strategy written to the NFT",
  "Стратегія в NFT пошкоджена (хеш не збігся).": "The NFT strategy is damaged (hash mismatch).",
  "Стратегія змінилась після виставлення.": "The strategy changed after listing.",
  "Стратегія не влазить в одну транзакцію: скороти правила.": "The strategy does not fit in one transaction: shorten the rules.",
  "Стратегія не та, що в лістингу.": "The strategy is not the one in the listing.",
  "Стратегія та сама: нічого не змінено.": "Same strategy: nothing changed.",
  "Сховати перевірку": "Hide check",
  "Сховати угоди": "Hide trades",
  "Твій лістинг": "Your listing",
  "Тейк-профіт, % (1–500)": "Take-profit, % (1–500)",
  "У NFT ще немає стратегії на ланцюгу. Збережи стратегію.": "The NFT has no on-chain strategy yet. Save a strategy.",
  "У гаманці вже": "The wallet already has",
  "У крана сервера скінчились devnet SOL.": "The server faucet is out of devnet SOL.",
  "У ланцюгу ще інша версія. Зачекай кілька секунд.": "The chain still shows another version. Wait a few seconds.",
  "У правилах лише латиниця, числа, ; < > = !": "Rules allow only Latin letters, numbers, ; < > = !",
  "У правилах лише латиниця, числа, ;": "Rules allow only Latin letters, numbers, ;",
  "У цьому NFT ще немає стратегії на ланцюгу (або атрибути пише не сервер).": "This NFT has no on-chain strategy yet (or the server does not write its attributes).",
  "Угоди за APR (": "Trades behind APR (",
  "Формула: PnL / найбільша ставка × 365 / днів × 100; вікно від max(зараз − 7/30д, зміни), щонайменше 1 день; лише угоди, відкриті після зміни.": "Formula: PnL / largest stake × 365 / days × 100; window from max(now − 7/30d, change), at least 1 day; only trades opened after the change.",
  "Хеш (sh)": "Hash (sh)",
  "Хеш стратегії в NFT не збігся.": "The NFT strategy hash does not match.",
  "Це твій лістинг.": "This is your listing.",
  "Цей гаманець уже отримав SOL сьогодні.": "This wallet already got SOL today.",
  "Ціна": "Price",
  "Ціна від 0.001 до 100 SOL.": "Price from 0.001 to 100 SOL.",
  "Ціна змінилась. Онови ринок.": "The price changed. Refresh the market.",
  "Ціна, SOL": "Price, SOL",
  "Читаю ринок…": "Reading the market…",
  "Ще": "Another",
  "більша за": "greater than",
  "вимкнена в стратегії NFT.": "is off in the NFT strategy.",
  "відкрито": "open",
  "год": "h",
  "год після зміни стратегії.": "h after a strategy change.",
  "заморожено сервером на ланцюгу": "frozen by the server on chain",
  "збалансований": "balanced",
  "комісія": "fee",
  "не заморожено": "not frozen",
  "нових угод чекають наступного запису.": "new trades wait for the next write.",
  "поза коридором": "outside the band",
  "помилка": "error",
  "правил.": "rules.",
  "ризиковий": "risky",
  "символів.": "characters.",
  "спокійний": "calm",
  "угод": "trades",
  "угоди симульовані": "trades simulated",
  "хв": "min",
  "хв не в стратегії NFT.": "min is not in the NFT strategy.",
  "ще ні": "not yet",
  "замок продажу 240 год": "sale lock 240 h",
  "✓ Збігається:": "✓ Matches:",
  "✓ збігається з параметрами": "✓ matches the params",
  "✗ НЕ збігається": "✗ does NOT match",
  "✗ Не збігається:": "✗ Does not match:",
};
